spring:
  datasource:
    password: root
    username: root
    url: jdbc:mysql:///openapi?useUnicode=true&characterEncoding=utf8
    type: com.alibaba.druid.pool.DruidDataSource
  rabbitmq:
    host: localhost
    port: 5672
